#!/bin/bash

[% c("var/set_default_env") -%]

mkdir -p [% dest_dir %]/[% c("filename") %]
[% FOREACH lang = c('var/locales') %]
  [% SET lang = tmpl(lang) %]
  [% SET filename = c("var/input_filename") _ '/' _ lang _ '.xpi'; %]
  cp -a [% filename %] [% dest_dir %]/[% c("filename") %]/
[% END %]
