#!/bin/bash
[% c("var/set_default_env") -%]
[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
distdir=/var/tmp/dist
builddir=/var/tmp/build/[% project %]
mkdir -p $distdir
tar -C /var/tmp/dist -xf [% c('input_files_by_name/clang') %]

mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz

# Now prepare the offline build
# Move the directory for hardcoding the path in .cargo/config
mv /var/tmp/build/[% project %]-[% c('version') %] $builddir
cd $builddir

make WASM_CC=$distdir/clang/bin/clang \
     WASM_AR=$distdir/clang/bin/llvm-ar \
     WASM_NM=$distdir/clang/bin/llvm-nm \
     SYSROOT=$(pwd)/wasi-sysroot \
     INSTALL_DIR=$distdir/[% project %]
make install

cd $distdir/[% project %]/[% project %]
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
