#!/bin/bash
[% c("var/set_default_env") -%]
distdir=/var/tmp/dist
mkdir -p $distdir
tar -C /var/tmp/dist -xf $rootdir/[% c('input_files_by_name/rust') %]
export PATH="/var/tmp/dist/rust/bin:$PATH"

mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz
mv /var/tmp/build/[% project %]-[% c('version') %] /var/tmp/build/[% project %]
cd /var/tmp/build/[% project %]
# Now prepare the offline build
mv $rootdir/vendor .
mkdir .cargo
cat > .cargo/config << 'EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/var/tmp/build/cbindgen/vendor"
EOF

cargo build --release --frozen --target=x86_64-unknown-linux-gnu

cd $distdir/[% project %]
[% c('tar', {
        tar_src => [ '.' ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
