#!/bin/bash
[% c("var/set_default_env") -%]
[% pc('go', 'var/setup', { go_tarfile => c('input_files_by_name/go') }) %]
[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
tar -C /var/tmp/dist -xf $rootdir/[% c('input_files_by_name/binutils') %]
export PATH="/var/tmp/dist/binutils/bin:$PATH"
tar -C /var/tmp/dist -xf [% c('input_files_by_name/go-socks5') %]
tar -C /var/tmp/dist -xf [% c('input_files_by_name/zap') %]
tar -C /var/tmp/dist -xf [% c('input_files_by_name/goptlib') %]
distdir="/var/tmp/dist/[% project %]"
[% c("var/set_PTDIR_DOCSDIR") -%]
mkdir -p $PTDIR
mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz
cd /var/tmp/build/[% project %]-[% c('version') %]

# XXX: Third-party code gets built first. Ideally we want to do that in own
# projects which is slightly trickier as we are supposed to use the code checked
# into this repo. I guess we could use the same repo every time and just build
# the repsective third-party code which kind of feels weird. But we should think
# about whether we need that first anyway, see #26920 comment:5.
mkdir third_party/libs
# We already have GMP, so just copy it over.
tar -C /var/tmp/dist -xf $rootdir/[% c('input_files_by_name/gmp') %]
export CGO_CXXFLAGS="-I/var/tmp/dist/gmp/include"
cp /var/tmp/dist/gmp/lib/libgmp.a third_party/libs/
# re2
cd third_party/re2
make -j[% c("buildconf/num_procs") %]
cp obj/libre2.a ../libs/
# openfst
cd ../openfst
./configure --enable-static=yes
make -j[% c("buildconf/num_procs") %]
cp src/lib/.libs/libfst.a ../libs/
cp src/script/.libs/libfstscript.a ../libs/
cd ../../

# Building Marionette
marionette_path="$GOPATH/src/github.com/redjack"
mkdir -p $marionette_path
ln -sf "$PWD" $marionette_path/marionette
# We build inside the GOPATH as `go install` would fail otherwise.
cd $marionette_path/marionette
go build
go install ./cmd/marionette
cp $GOPATH/bin/marionette* $PTDIR

cd $distdir
[% c('tar', {
        tar_src => [ '.' ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
